# coding: utf-8

"""
    Flexify.IO User REST API

    + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API  # noqa: E501

    OpenAPI spec version: 2.8.0-SNAPSHOT
    Contact: info@flexify.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flexify_api
from flexify_api.api.cloud_locations_controller_api import CloudLocationsControllerApi  # noqa: E501
from flexify_api.rest import ApiException


class TestCloudLocationsControllerApi(unittest.TestCase):
    """CloudLocationsControllerApi unit test stubs"""

    def setUp(self):
        self.api = flexify_api.api.cloud_locations_controller_api.CloudLocationsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_available_locations_for_current_user(self):
        """Test case for get_available_locations_for_current_user

        getAvailableLocationsForCurrentUser  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
