# coding: utf-8

"""
    Flexify.IO User REST API

    + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API  # noqa: E501

    OpenAPI spec version: 2.11.0-dev
    Contact: info@flexify.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flexify_api
from flexify_api.models.create_virtual_bucket_request import CreateVirtualBucketRequest  # noqa: E501
from flexify_api.rest import ApiException


class TestCreateVirtualBucketRequest(unittest.TestCase):
    """CreateVirtualBucketRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateVirtualBucketRequest(self):
        """Test CreateVirtualBucketRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flexify_api.models.create_virtual_bucket_request.CreateVirtualBucketRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
