# coding: utf-8

"""
    Flexify.IO User REST API

    + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API  # noqa: E501

    OpenAPI spec version: 2.7.0-SNAPSHOT
    Contact: info@flexify.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flexify_api
from flexify_api.models.payment_add_request import PaymentAddRequest  # noqa: E501
from flexify_api.rest import ApiException


class TestPaymentAddRequest(unittest.TestCase):
    """PaymentAddRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentAddRequest(self):
        """Test PaymentAddRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flexify_api.models.payment_add_request.PaymentAddRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
