# coding: utf-8

"""
    Flexify.IO User REST API

    + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API  # noqa: E501

    OpenAPI spec version: 2.4.2
    Contact: info@flexify.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flexify_api_client
from api.endpoints_controller_api import EndpointsControllerApi  # noqa: E501
from flexify_api_client.rest import ApiException


class TestEndpointsControllerApi(unittest.TestCase):
    """EndpointsControllerApi unit test stubs"""

    def setUp(self):
        self.api = api.endpoints_controller_api.EndpointsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attach_storage_to_endpoint(self):
        """Test case for attach_storage_to_endpoint

        Attach the storage to the endpoint  # noqa: E501
        """
        pass

    def test_detach_storage_from_endpoint(self):
        """Test case for detach_storage_from_endpoint

        Detach the storage from the endpoint  # noqa: E501
        """
        pass

    def test_disable(self):
        """Test case for disable

        Disable the endpoint  # noqa: E501
        """
        pass

    def test_enable(self):
        """Test case for enable

        Enable the endpoint  # noqa: E501
        """
        pass

    def test_get_endpoint_details(self):
        """Test case for get_endpoint_details

        Get endpoint details  # noqa: E501
        """
        pass

    def test_get_endpoints_for_current_user(self):
        """Test case for get_endpoints_for_current_user

        Get endpoint for current user. This method will create new endpoint if no endpoints exist for user  # noqa: E501
        """
        pass

    def test_set_default_storage(self):
        """Test case for set_default_storage

        Set given storage as default for the endpoint  # noqa: E501
        """
        pass

    def test_update_endpoint(self):
        """Test case for update_endpoint

        Update attributes of the endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
