# coding: utf-8

"""
    Flexify.IO User REST API

    + Get API token + Authorize using `Bearer TOKEN` + Enjoy Flexify.IO REST API  # noqa: E501

    OpenAPI spec version: 2.12.9
    Contact: info@flexify.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flexify_api
from flexify_api.models.user_config import UserConfig  # noqa: E501
from flexify_api.rest import ApiException


class TestUserConfig(unittest.TestCase):
    """UserConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserConfig(self):
        """Test UserConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flexify_api.models.user_config.UserConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
