# coding: utf-8

"""
    Flexify.IO User REST API

    + Get API token + Authorize using `Bearer TOKEN` + Enjoy Flexify.IO REST API  # noqa: E501

    OpenAPI spec version: 2.12.10.hf4
    Contact: info@flexify.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flexify_api
from flexify_api.models.token_configuration import TokenConfiguration  # noqa: E501
from flexify_api.rest import ApiException


class TestTokenConfiguration(unittest.TestCase):
    """TokenConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenConfiguration(self):
        """Test TokenConfiguration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flexify_api.models.token_configuration.TokenConfiguration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
