# coding: utf-8

"""
    Flexify.IO User REST API

    + Get API token + Authorize using `Bearer TOKEN` + Enjoy Flexify.IO REST API  # noqa: E501

    OpenAPI spec version: 2.12.7-SNAPSHOT
    Contact: info@flexify.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flexify_api
from flexify_api.models.storage_provider import StorageProvider  # noqa: E501
from flexify_api.rest import ApiException


class TestStorageProvider(unittest.TestCase):
    """StorageProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageProvider(self):
        """Test StorageProvider"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flexify_api.models.storage_provider.StorageProvider()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
