# coding: utf-8

"""
    Flexify.IO User REST API

    + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API  # noqa: E501

    OpenAPI spec version: 2.4.2
    Contact: info@flexify.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flexify_api_client
from flexify_api_client.io.flexify.apiclient.model.cloud_location import CloudLocation  # noqa: E501
from flexify_api_client.rest import ApiException


class TestCloudLocation(unittest.TestCase):
    """CloudLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudLocation(self):
        """Test CloudLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flexify_api_client.models.cloud_location.CloudLocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
