# coding: utf-8

"""
    Flexify.IO User REST API

    + Get API token + Authorize using `Bearer TOKEN` + Enjoy Flexify.IO REST API  # noqa: E501

    OpenAPI spec version: 2.12.5-SNAPSHOT
    Contact: info@flexify.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import flexify_api
from flexify_api.models.add_impersonate_from_user_request import AddImpersonateFromUserRequest  # noqa: E501
from flexify_api.rest import ApiException


class TestAddImpersonateFromUserRequest(unittest.TestCase):
    """AddImpersonateFromUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddImpersonateFromUserRequest(self):
        """Test AddImpersonateFromUserRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = flexify_api.models.add_impersonate_from_user_request.AddImpersonateFromUserRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
