# coding: utf-8

"""
    Flexify.IO User REST API

    + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API  # noqa: E501

    OpenAPI spec version: 2.6
    Contact: info@flexify.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BucketStat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bytes': 'int',
        'last_refreshed': 'datetime',
        'objects': 'int',
        'stat_state': 'str'
    }

    attribute_map = {
        'bytes': 'bytes',
        'last_refreshed': 'lastRefreshed',
        'objects': 'objects',
        'stat_state': 'statState'
    }

    def __init__(self, bytes=None, last_refreshed=None, objects=None, stat_state=None):  # noqa: E501
        """BucketStat - a model defined in Swagger"""  # noqa: E501

        self._bytes = None
        self._last_refreshed = None
        self._objects = None
        self._stat_state = None
        self.discriminator = None

        if bytes is not None:
            self.bytes = bytes
        if last_refreshed is not None:
            self.last_refreshed = last_refreshed
        if objects is not None:
            self.objects = objects
        if stat_state is not None:
            self.stat_state = stat_state

    @property
    def bytes(self):
        """Gets the bytes of this BucketStat.  # noqa: E501

        Bytes in this bucket/container  # noqa: E501

        :return: The bytes of this BucketStat.  # noqa: E501
        :rtype: int
        """
        return self._bytes

    @bytes.setter
    def bytes(self, bytes):
        """Sets the bytes of this BucketStat.

        Bytes in this bucket/container  # noqa: E501

        :param bytes: The bytes of this BucketStat.  # noqa: E501
        :type: int
        """

        self._bytes = bytes

    @property
    def last_refreshed(self):
        """Gets the last_refreshed of this BucketStat.  # noqa: E501

        Last success refresh operation complete timestamp  # noqa: E501

        :return: The last_refreshed of this BucketStat.  # noqa: E501
        :rtype: datetime
        """
        return self._last_refreshed

    @last_refreshed.setter
    def last_refreshed(self, last_refreshed):
        """Sets the last_refreshed of this BucketStat.

        Last success refresh operation complete timestamp  # noqa: E501

        :param last_refreshed: The last_refreshed of this BucketStat.  # noqa: E501
        :type: datetime
        """

        self._last_refreshed = last_refreshed

    @property
    def objects(self):
        """Gets the objects of this BucketStat.  # noqa: E501

        Objects in this bucket/container  # noqa: E501

        :return: The objects of this BucketStat.  # noqa: E501
        :rtype: int
        """
        return self._objects

    @objects.setter
    def objects(self, objects):
        """Sets the objects of this BucketStat.

        Objects in this bucket/container  # noqa: E501

        :param objects: The objects of this BucketStat.  # noqa: E501
        :type: int
        """

        self._objects = objects

    @property
    def stat_state(self):
        """Gets the stat_state of this BucketStat.  # noqa: E501

        State of the bucket/container  # noqa: E501

        :return: The stat_state of this BucketStat.  # noqa: E501
        :rtype: str
        """
        return self._stat_state

    @stat_state.setter
    def stat_state(self, stat_state):
        """Sets the stat_state of this BucketStat.

        State of the bucket/container  # noqa: E501

        :param stat_state: The stat_state of this BucketStat.  # noqa: E501
        :type: str
        """
        allowed_values = ["NONE", "CALCULATING", "REFRESHING", "FAILED", "CANCELED", "UPDATED"]  # noqa: E501
        if stat_state not in allowed_values:
            raise ValueError(
                "Invalid value for `stat_state` ({0}), must be one of {1}"  # noqa: E501
                .format(stat_state, allowed_values)
            )

        self._stat_state = stat_state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BucketStat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
